name: Alerts

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes (adjust as you like)

jobs:
  signal:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

          - name: Check secrets presence (no values printed)
  run: |
    python - <<'PY'
    import os
    print("BOT:", "set" if os.getenv("TELEGRAM_BOT_TOKEN") else "missing")
    print("CHAT:", "set" if os.getenv("TELEGRAM_CHAT_ID") else "missing")
    PY

      - name: Run Signal Job
        run: python signal_job.py --assets "BTC/USDT,ETH/USDT" --timeframes "5m,1h,4h" --limit 1000 --entry_long 60 --entry_short 40 --exit_warn 55 --exit_hard 45
