name: test-telegram
on:
  workflow_dispatch: {}   # manuell startbar
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send test message to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            --data-urlencode text="✅ SilentTrader online – Test aus GitHub Actions"
